# set the base image to Debian
# https://hub.docker.com/_/debian/
FROM debian:latest
WORKDIR "/application"
ENTRYPOINT ["tail", "-f", "/dev/null"]
# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# update the repository sources list
# and install dependencies
RUN apt-get update \
    && apt-get install -y curl \
    && apt-get install -y vim \
    && apt-get install -y git \
    && apt-get -y autoclean

# nvm environment variables
RUN mkdir /usr/local/nvm
ENV NVM_DIR /usr/local/nvm
ENV NODE_VERSION 14.17.3
ENV NVM_INSTALL_PATH $NVM_DIR/versions/node/v$NODE_VERSION
# install nvm
# https://github.com/creationix/nvm#install-script
RUN curl --silent -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash

# install node and npm
# RUN source $NVM_DIR/nvm.sh \
#     && nvm install --lts \
#     && nvm alias default lts/* \
#     && nvm use default
RUN source $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# add node and npm to path so the commands are available
ENV NODE_PATH $NVM_DIR/v$NODE_VERSION/lib/node_modules
ENV PATH $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

# confirm installation
RUN node -v
RUN npm -v
